
## FILEPATHS
SIMULATION_PATH = '/scr/andukuri/assistant-gate-hgx/simulated-conversations'
LOGPROBS_PATH = '/scr/andukuri/assistant-gate-hgx/log-probs'
PERSONAS_PATH = '/scr/andukuri/assistant-gate-hgx/personas'
GOLD_PATH = '/scr/andukuri/assistant-gate-hgx/gold-responses'
PROMPT_PATH = '/scr/andukuri/assistant-gate-hgx/prompts'
SFT_DATA_PATH = '/scr/andukuri/assistant-gate-hgx/sft-data'
CONTENT_VIOLATIONS_PATH = '/scr/andukuri/assistant-gate-hgx/content-violations'
FIGURES_PATH = '/scr/andukuri/assistant-gate-hgx/figures'
WINRATE_PATH = '/scr/andukuri/assistant-gate-hgx/win-rates'
MODELRESPONSE_PATH = '/scr/andukuri/assistant-gate-hgx/model-responses'
SPECIFICITY_PATH = '/scr/andukuri/assistant-gate-hgx/specificity-ratings/'
VERSION = 'star-1'
VERSION_2 = 'star-2'
VERSION_AG = 'star-1-ag'
VERSION_2_BSFT = 'star-2-bsft'
VERSION_2_MISTRAL_ABLATION = 'star-2-mistral-ablation'
VERSION_1_ESFT = 'star-1-esft'
VERSION_3_QSFT = 'star-3-qsft'
VERSION_3_MISTRAL_ABLATION = 'star-3-mistral-ablation'
